dbt_system_tables_mart:
  target: local
  outputs:
    #    #run DBT locally from your IDE and execute on a SQL warehouse (https://docs.getdbt.com/reference/warehouse-setups/databricks-setup)
    #    #Make sure you have pip install dbt-databricks in your local env
    #    #Run the project locally with:
    #    #DBT_DATABRICKS_HOST=xxx.cloud.databricks.com  DBT_DATABRICKS_HTTP_PATH=/sql/1.0/warehouses/xxxx DBT_DATABRICKS_TOKEN=dapixxxx dbt run
    local:
      type: databricks
      catalog: rama
      schema: "rd_test1"
      host: "cust-e2-us-west-2.cloud.databricks.com"
      http_path: "/sql/1.0/warehouses/c8ee309aef0561dc" #SQL warehouse Connection details
      token: "dapi9c66f1419f51c5e02669744c2ad2781c" # Personal Access Token (PAT)
      # auth_type: oauth
      threads: 3

    staging:
      type: databricks
      catalog: main
      schema: dbt_system_tables
      host: "cust-e2-us-west-2.cloud.databricks.com"
      http_path: "/sql/1.0/warehouses/c8ee309aef0561dc" #SQL warehouse Connection details
      token: "dapi9c66f1419f51c5e02669744c2ad2781c" # Personal Access Token (PAT)
      # auth_type: oauth
      threads: 3




